from PIL import Image
from os import walk
from datetime import datetime as dt

# given an input file generated by photo_dir_name_printer.py and a directory this will delete photos in the directory
# that are not in the text file
DIR_TO_CLEANUP = '/Users/justin.warner/Pictures/412_0426/'
PHOTO_NAMES_INVENTORY_FILE = ''

_, _, filenames = next(walk(SOURCE_PATH))
filenames = sorted(filenames)
prevnum = None
deleted = []
for name in filenames:
    print(name)
    if name.lower().endswith('.jpg'):
        num = int(name[4:8])
        if prevnum and prevnum + 1 != num:
            while prevnum + 1 != num:
                deleted.append(prevnum + 1)
                prevnum += 1
        prevnum = num

print(deleted)
