import os, pathlib

# given an input file generated by photo_dir_name_printer.py and a directory this will delete photos in the directory
# that are not in the text file
DIR_TO_CLEANUP = 'D:/Pictures/All/Vacation/2023/2023_09_15 Vancouver Island Port Hardy Diving/'
DIR_TO_CLEANUP = 'D:/Pictures/All/Underwater/Mainland Dives/2023_10_14 KVI Tower/'
PHOTO_NAMES_INVENTORY_FILE = 'D:/OneDrive/Documents/vashon-pics.txt'

INVENTORY_PREFIX = '/Users/justin.warner/Pictures/488_1014'
CLEANUP_PREFIX = 'D:/Pictures/All/Vacation/2023/'
CLEANUP_PREFIX = 'D:/Pictures/All/Underwater/Mainland Dives/2023_10_14 KVI Tower'


# populates the given filePaths set with strings consisting of (absolute dir path + filename) for all files in
# directory and its subdirs
def getContents(directory, filePaths):
    dirCount = 0
    fileCount = 0
    for root, dirs, files in sorted(os.walk(directory)):
        parentDir = str(pathlib.PureWindowsPath(root).as_posix()).replace(CLEANUP_PREFIX, "")
        if '2023_09_25' in parentDir:
            continue
        dirCount += 1
        fileCount += len(files)
        for file in sorted(files):
            filePaths.add(parentDir + '/' + file)
    print('{} directories (including root) and {} files'.format(dirCount, fileCount))


# get the files currently present (a lot should be deleted)
filePathsToClean = set()
getContents(DIR_TO_CLEANUP, filePathsToClean)

# get the files we want remaining at the end
filePathsDesired = set()
with open(PHOTO_NAMES_INVENTORY_FILE) as f:
    curDir = ''
    for line in f:
        if line.startswith('/'):
            curDir = line.strip().replace(INVENTORY_PREFIX, "")
        elif line.strip().startswith('IMG'):
            filePathsDesired.add(curDir + '/' + line.strip())

print("{} current pictures present".format(len(filePathsToClean)))
print("{} pictures desired".format(len(filePathsDesired)))
for desired in filePathsDesired:
    if desired in filePathsToClean:
        filePathsToClean.remove(desired)
print("{} pictures to delete".format(len(filePathsToClean)))

# debug info
i = 0
for path in filePathsToClean:
    print(path)
    i += 1
    if i > 3: break
i = 0
for path in filePathsDesired:
    print(path)
    i += 1
    if i > 3: break

for toDelete in filePathsToClean:
    print('deleting ' + CLEANUP_PREFIX + toDelete)
    # os.remove(CLEANUP_PREFIX + toDelete)
