import os, pathlib

# given an input file generated by photo_dir_name_printer.py and a directory this will delete photos in the directory
# that are not in the text file
DIR_TO_CLEANUP = 'D:/Pictures/Vacation/2024/2024_06 Socorro/'
# DIR_TO_CLEANUP = 'D:/Pictures/Underwater/Mainland Dives/2023_10_14 KVI Tower/'
PHOTO_NAMES_INVENTORY_FILE = 'D:/OneDrive/Documents/socorro-photo-names.txt'

# prefix in the inventory file from macbook to remove
INVENTORY_PREFIX = '/Users/justin.warner/Pictures/Socorro'
# CLEANUP_PREFIX should match the DIR_TO_CLEANUP field without the trailing /
CLEANUP_PREFIX = 'D:/Pictures/Vacation/2024/2024_06 Socorro'


# populates the given filePaths set with strings consisting of (absolute dir path + filename) for all files in
# directory and its subdirs
def getContents(directory, filePaths):
    dirCount = 0
    fileCount = 0
    for root, dirs, files in sorted(os.walk(directory)):
        parentDir = str(pathlib.PureWindowsPath(root).as_posix()).replace(CLEANUP_PREFIX, "")
        if 'Socorro Top' in parentDir:
            print('skipping Socorro Top')
            continue
        dirCount += 1
        fileCount += len(files)
        for file in sorted(files):
            filePaths.add(parentDir + '/' + file)
    print('{} directories (including root) and {} files'.format(dirCount, fileCount))


# get the files currently present (a lot should be deleted)
filePathsToClean = set()
getContents(DIR_TO_CLEANUP, filePathsToClean)

# get the files we want remaining at the end
filePathsDesired = set()
with open(PHOTO_NAMES_INVENTORY_FILE) as f:
    curDir = ''
    for line in f:
        if line.startswith('/'):
            curDir = line.strip().replace(INVENTORY_PREFIX, "")
        elif line.strip().startswith('IMG') or line.strip().startswith('MVI'):
            filePathsDesired.add(curDir + '/' + line.strip())

print("{} current pictures present".format(len(filePathsToClean)))
print("{} pictures desired".format(len(filePathsDesired)))
for desired in filePathsDesired:
    if desired in filePathsToClean:
        filePathsToClean.remove(desired)
print("{} pictures to delete".format(len(filePathsToClean)))

# debug info for any path confusion
# i = 0
# for path in filePathsToClean:
#     print(path)
#     i += 1
#     if i > 3: break
# i = 0
# for path in filePathsDesired:
#     print(path)
#     i += 1
#     if i > 3: break

for toDelete in filePathsToClean:
    print('deleting ' + CLEANUP_PREFIX + toDelete)
    os.remove(CLEANUP_PREFIX + toDelete)
